config/routes.rb
Rails.application.routes.draw do
  get '/products', to: 'products#index'
  get '/products/new', to: 'products#new'
  post '/products', to: 'products#create'
  get 'products/:id', to: 'product#show',as: 'product'
  get '/products/:id/edit', to: 'products#edit', as: 'edit_product' 
  patch '/products/:id', to: 'products#update'
  put '/products/:id', to: 'products#update'
delete '/products/:id', to: 'products#delete'
  #resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def delete
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
    


  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product  do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </div>
    <div>
        <%= f.submit "Guardar", disable_with: 'Procesando...' %>
    </div>
<% end %>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<%= link_to "Nuevo Producto", products_new_path %>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @product.each do |product| %>
        <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td>
                <%= link_to "Editar",edit_product_path(product) %>
                <%= link_to "Elimnar",product,method: :delete, data:{confirm:"Desea eliminar este articulo?"} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/products/new.html.erb
<%= form_for @product  do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </div>
    <div>
        <%= f.submit "Guardar", disable_with: 'Procesando...' %>
    </div>
<% end %>